name: RunDocGenerator

on:
  release:
      types: [created]
    
jobs:
  generate_job:
    runs-on:  'ubuntu-latest'
    
    steps:
      - name: Invoke documentation generator
        run: curl -X POST -H 'Authorization:token ${{secrets.DOCS_TOKEN}}' -d '{"event_type":"generate"}' https://api.github.com/repos/mianalysis/mianalysis.github.io/dispatches
